version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_turismo
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - turismo_net

volumes:
  mysql_data:

networks:
  turismo_net:
